# fly.toml app configuration file generated for crcportfolio on 2023-09-13T10:53:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "crcportfolio"
primary_region = "ewr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
